### ISSUE TITLE
Failure to simulate `seas_pacf` feature....

### ISSUE THREAD

**Issue by michael135** [ykang/tsgeneration#10]
Hello, I had en error, when I tried to simulate `seas_pacf` feature:
```
x <- generate_ts_with_target(n = 2, ts.length = 60, freq = 1, seasonal = 0,
                             features = c('pacf_features'),
                             selected.features = c('seas_pacf'),
                             target = c(.01))
```
The output is:
```
Error in { : task 1 failed - "Unknown column `seas_pacf`
Backtrace:
```

**What was done wrong?**

**Comment by michael135** [comment]
If we will change `freq = 2` it will run without en error.

**Comment by ykang** [comment]
Yes because  `seas_pacf` is a feature for seasonal time series. If `freq = 1`, `seas_pacf` is not in the candidate set of features.

**Comment by michael135** [comment]
thank you @ykang ,
I would recommend to add it at function documentation.
For example at docstring of https://github.com/ykang/tsgeneration/blob/master/R/generate_ts_with_target.R

Currently, it's **unclear** from documentation, which value of freq are relevant for what.

**Comment by ykang** [comment]
Thanks Michael for your suggestion.

Sent from my iPhone

On Apr 22, 2019, at 13:31, Michael Dym <notifications@github.com<mailto:notifications@github.com>> wrote:


thank you @ykang<https://github.com/ykang> ,
I would recommend to add it at function documentation.
For example at docstring of https://github.com/ykang/tsgeneration/blob/master/R/generate_ts_with_target.R

Currently, it's unclear from documentation, which value of freq are relevant for what.
