### ISSUE TITLE
Doesn't work with Linux (Ubuntu)

### ISSUE THREAD

**Issue by michael135** [ykang/tsgeneration#11]
Doesn't work with Linux (Ubuntu):

has the following error:
```
mcfork(): unable to create pipe
Calls: generator... <Anonymous> -> makeForkCluster -> newForkNode -> mcFork

Execution halted.
```

![image (2)](https://user-images.githubusercontent.com/8559652/59680815-f9b81680-91da-11e9-9737-61ee110f837b.png)

**Comment by feng-li** [comment]
I think this is not a `tsgeneration` problem. You may consult with `doMC` package maintainers.
