### ISSUE TITLE
how to modified generate_ts_with_target function to other time series feature?

### ISSUE THREAD

**Issue by ru81git454** [ykang/tsgeneration#14]
Hi,
I found this package is interesting and helpful to my research.  and i want to use same approach to other feature that not in tsfeatures package.
I also found tsfeatures package support Compengine feature set from Fulcher. I want to try other feature set(catch22) https://github.com/chlubba/catch22  also from Fulcher.
How should I modified function to match other features not in tsfeatures?

Thanks for helping

**Comment by ykang** [comment]
Hi,
The `tsfeatures` package is flexible to use user-defined functions to calculate time series features. You can put your own feature calculation function into the second parameter ('features') of `tsfeatures::tsfeatures()` (refer to the help documentation). `generate_ts_with_target()` also has a parameter called 'features', which works similarly.

**Comment by ru81git454** [comment]
Thanks,I will try!
