### ISSUE TITLE
can it generate multivariate time series wit mixture continues and categorical data ?

### ISSUE THREAD

**Issue by Sandy4321** [ykang/tsgeneration#31]
great code thanks

only can it generate multivariate time series wit mixture continues and categorical data 
meaning 
several time series with continues  data
and 
several time series with categorical data

but there is some dependency between these time series ?

**Comment by feng-li** [comment]
At the moment. `gratis` only generates univariate time series. Generating multivariate yet mixed with discrete and continuous time series requires some external inputs. You may need to utilize some version of autoregressive copulas for such task.

**Comment by Sandy4321** [comment]
great 
can you share link to such a repo on github pls?

**Comment by feng-li** [comment]
Try the `BiCopSim` function from the `VineCopula` package.

**Comment by Sandy4321** [comment]
https://github.com/feng-li
thanks
but
https://github.com/tnagler/VineCopula
BiCopSim: Simulates from a bivariate copula.

BiCopSim is for simulation, not classification

**Comment by Sandy4321** [comment]
@feng-li 
thanks
but
https://github.com/tnagler/VineCopula
BiCopSim: Simulates from a bivariate copula.

BiCopSim is for simulation, not classification
