### ISSUE TITLE
What is the difference between several features, which apparantely related to seasonality?

### ISSUE THREAD

**Issue by michael135** [ykang/tsgeneration#6]
What is the difference between following features?

- seasonal_strength
- seasonal_strength1
- seasonal_strength2
- seas_acf1
- seas_pacf1

And in particular if **seasonal_strength = 1** is it possible, that  **seas_acf1=0**?

I looked through [`tsgeneration paper`](https://robjhyndman.com/papers/TSgeneration.pdf), but I didn't find. Please let me know if I miss something.

**Comment by ykang** [comment]
seasonal_strength1 and seasonal_strength2 are for multi-seasonal time series, representing seasonal_strength for the 1st and 2nd seasonal component.

**Comment by michael135** [comment]
If I choose just **seasonal_strength**, it means, that there will be just 1 kind of seasonality?

**Comment by ykang** [comment]
Yes.

Sent from my iPhone

On Mar 6, 2019, at 19:03, Michael Dym <notifications@github.com<mailto:notifications@github.com>> wrote:


If I choose just seasonal_strength, it means, that there will be just 1 kind of seasonality?

**Comment by michael135** [comment]
Does it makes sence if I choose:

- seasonal_strength = 1 (maximum)

When:

- seas_acf1 = 0
- seas_pacf1 = 0

Isn't it some kind of contradiction?

**Comment by feng-li** [comment]
I don't think that is a realistic setting reflecting the real world.

**Comment by michael135** [comment]
Just to assure that we are on the same page, in order to create "realistic" seasonal time series.

There should be:

- seasonal_strength > 0
- seas_acf1 > 0
- seas_pacf1 > 0

Or some additional features also should be greater than 0 ?

**Comment by feng-li** [comment]
I think you just need to set `seasonal_strength > 0` and leave `seas_acf1` and `seas_pacf1` as `0` (in the Shiny app, `0` really means unrestricted), unless you have some specific interest (target) of `acf` and `pacf`.

**Comment by michael135** [comment]
thank you @feng-li, it's very helpful information.
Without GUI, the logic is the same?
If I don't specify "some feature" it's not necessary `0`?
