### ISSUE TITLE
Features from GUI appears to be very different from the features in CLI

### ISSUE THREAD

**Issue by michael135** [ykang/tsgeneration#8]
Features from GUI appears to be very different from the features in CLI

For example:
https://ebsmonash.shinyapps.io/tsgeneration/
or at run_tsgeneration_app().

Where I can find any documentation of "all available features", and to which group they belong?

**Comment by ykang** [comment]
Please refer to the appendix of our working paper on arxiv: https://arxiv.org/abs/1903.02787.

**Comment by michael135** [comment]
@ykang , thank you!
