### ISSUE TITLE
Where I can find description  for the features?

### ISSUE THREAD

**Issue by michael135** [ykang/tsgeneration#9]
Where I can find description (hopefully, including some relevant equations) for the features?

For example **time_var_shift**.

I found some descriptions in **tsfeatures package**, but it doesn't cover all features, as well as the original paper.

**Comment by Neverstop7** [comment]
This paper might be useful (I haven't read it yet): https://arxiv.org/ftp/arxiv/papers/1903/1903.02787.pdf
